---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-apps-k8s-appscode-com-v1-petset
  failurePolicy: Fail
  name: mpetset-v1.kb.io
  rules:
  - apiGroups:
    - apps.k8s.appscode.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - petsets
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apps-k8s-appscode-com-v1-petset
  failurePolicy: Fail
  name: vpetset-v1.kb.io
  rules:
  - apiGroups:
    - apps.k8s.appscode.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - petsets
  sideEffects: None
